### ISSUE TITLE
support for osmc

### ISSUE THREAD

**Issue by fadern** [suuhm/raspi_mpeg_license_patch.sh#1]
Hi,

is it possible to get support for osmc?

https://www.reddit.com/r/raspberry_pi/comments/8sg0a6/patch_for_mpeg2_vc1_license_again_for_osmc/

**Comment by suuhm** [comment]
hi I've  just added some Multi OS Support, plaese check out with adding like ```--patch-now --os=osmc```

**Comment by fadern** [comment]
Hi, Thank you!
My osmc is already patched so i have not been able to test the new script.

**Comment by fadern** [comment]
Hi again,
I have now tried the script at my rapi3 osmc. I doesnt seem to be working.

`root@osmc:/home/osmc# wget https://raw.githubusercontent.com/suuhm/raspi_mpeg_license_patch.sh/main/raspi_mpeg_license_patch.sh -qO- | bash -s -- --patch-now --os=osmc
   ____________________________________________________ 
  |><><><><><><><><><><><><><><><><><><><><><><><><><><|
  |  raspi_mpeg_license_patch v0.3b - (c)2021 suuhm    |
  |____________________________________________________|
                                                        
* Getting some necessary tools, maybe this take some time...
* First check mpeg2/vc activated?
MPG2=disabled
WVC1=disabled


* Getting Hexstring... May take some time...

main: line 38: xxd: command not found
main: line 39: xxd: command not found
* Not patched continue...
mount: /flash: mount point does not exist.
* set up patch now...
* Finished. success
New md5sum: b177e6dd1ecbfb20c2db0bcf86881739  /boot/start_x.elf
Old md5sum: b177e6dd1ecbfb20c2db0bcf86881739  /boot/start_x.elf.BACKUP

* Now, pls restart your device and check again.`

`root@osmc:/home/osmc# vcgencmd codec_enabled mpg2
mpg2=disabled
root@osmc:/home/osmc# vcgencmd codec_enabled vc1 
vc1=disabled`

**Comment by suuhm** [comment]
Hi, I just make some bugfixes here ( https://github.com/suuhm/raspi_mpeg_license_patch.sh/commit/74b96a894aaf216093e203a95405afecdfe8254c ) please test again.

**Comment by fadern** [comment]
`
root@osmc:/home/osmc# wget https://raw.githubusercontent.com/suuhm/raspi_mpeg_license_patch.sh/main/raspi_mpeg_license_patch.sh -qO- | bash -s -- --patch-now --os=osmc
bash: line 74: syntax error near unexpected token `}'
bash: line 74: `}'
`

**Comment by suuhm** [comment]
hi, thx for the report, can you plaese test it again, now there souldNn't have been any issues anymore :)

**Comment by fadern** [comment]
Now the script completes but it says that the system i already patched... But it says that the mpeg2/vc is disabled..

`root@osmc:/home/osmc# wget https://raw.githubusercontent.com/suuhm/raspi_mpeg_license_patch.sh/main/raspi_mpeg_license_patch.sh -qO- | bash -s -- --patch-now --os=osmc
   ____________________________________________________ 
  |><><><><><><><><><><><><><><><><><><><><><><><><><><|
  |  raspi_mpeg_license_patch v0.3b - (c)2021 suuhm    |
  |____________________________________________________|
                                                        
* Getting some necessary tools, maybe this take some time...
Tools already just here, continue...
* First check mpeg2/vc activated?
MPG2=disabled
WVC1=disabled


* Getting Hexstring... May take some time...

* Already Patched`

**Comment by suuhm** [comment]
Ok seems to be already patched. Just reboot and post please the full output with --check-only parameter instead of --patch-now

And again check under GPU /Mem Codec in your osmc settings screen directly

This should it look like:

```
 # ./raspi_mpeg_license_patch.sh --patch-now --os=osmc
   ____________________________________________________
  |><><><><><><><><><><><><><><><><><><><><><><><><><><|
  |  raspi_mpeg_license_patch v0.3b - (c)2021 suuhm    |
  |____________________________________________________|

* Getting some necessary tools, maybe this take some time...
Tools already just here, continue...
* First check mpeg2/vc activated?
MPG2=disabled
WVC1=disabled


* Getting Hexstring... May take some time...

* Not patched continue...
* set up patch now...
* Finished. success
New md5sum: 2d36518fe9461153cf23d04c144588b2  /flash/start.elf
Old md5sum: 68df876d73f90636bf9f4640959e31be  /flash/start.elf.BACKUP

* Now, pls restart your device and check again.
```
