### ISSUE TITLE
vcgencmd codec_enabled MPG2 ==> MPG2=disabled

### ISSUE THREAD

**Issue by nik2208** [suuhm/raspi_mpeg_license_patch.sh#2]
this is the output of the script --check-only 

  ____________________________________________________ 
  |><><><><><><><><><><><><><><><><><><><><><><><><><><|
  |  raspi_mpeg_license_patch v0.3b - (c)2021 suuhm    |
  |____________________________________________________|
                                                        
START.ELF not found. Searching for possible files:
---------------------------------------------

find: ‘/proc/8301/task/8301/net’: Invalid argument
find: ‘/proc/8301/net’: Invalid argument
/boot/start.elf.BACKUP
/boot/start.elf
/boot/start_cd.elf
/boot/start_db.elf
/boot/start_x.elf
/boot/start4.elf
/boot/start4cd.elf
/boot/start4db.elf
/boot/start4x.elf

---------------------------------------------

Please enter the full Path to the START.ELF: 
/boot/start.elf
* Getting some necessary tools, maybe this take some time...
Tools already just here, continue...
* First check mpeg2/vc activated?
MPG2=disabled
WVC1=disabled

* Getting Hexstring... May take some time...

* Already Patched

whats wrong?

**Comment by suuhm** [comment]
You had already patched the start.elf?
Seems strange ,so which os you're using?

**Comment by nik2208** [comment]
Yes I've already patched (using your script obviously) my rPI3 running raspiOS (latest version)

**Comment by suuhm** [comment]
Ok, can you please test the check with the /boot/start.elf.BACKUP file again? Whats the output here?

**Comment by nik2208** [comment]
|><><><><><><><><><><><><><><><><><><><><><><><><><><|
  |  raspi_mpeg_license_patch v0.3b - (c)2021 suuhm    |
  |____________________________________________________|
                                                        
START.ELF not found. Searching for possible files:
---------------------------------------------

find: ‘/proc/5552/task/5552/net’: Invalid argument
find: ‘/proc/5552/net’: Invalid argument
/boot/start.elf.BACKUP
/boot/start.elf
/boot/start_cd.elf
/boot/start_db.elf
/boot/start_x.elf
/boot/start4.elf
/boot/start4cd.elf
/boot/start4db.elf
/boot/start4x.elf

---------------------------------------------

Please enter the full Path to the START.ELF: 
/boot/start.elf.BACKUP
* Getting some necessary tools, maybe this take some time...
Tools already just here, continue...
* First check mpeg2/vc activated?
MPG2=disabled
WVC1=disabled


* Getting Hexstring... May take some time...

* Not patched continue...


* Check state xxd location +/- 1 line:
0009b610: 009e 7f00 47e9 3247 504d 1018 02e8 3336  ....G.2GPM....36
0009b620: 3248 47e9 3336 3248 0918 47e9 3447 504d  2HG.362H..G.4GPM
0009b630: 0518 47e9 3143 5657 c918 0060 009e 6900  ..G.1CVW...`..i.

* get GPUtemp every 5 secs... (STOP with Ctrl+C)
./raspi_mpeg_license_patch.sh: line 129: gputemp: command not found
./raspi_mpeg_license_patch.sh: line 129: gputemp: command not found
./raspi_mpeg_license_patch.sh: line 129: gputemp: command not found
./raspi_mpeg_license_patch.sh: line 129: gputemp: command not found
./raspi_mpeg_license_patch.sh: line 129: gputemp: command not found
./raspi_mpeg_license_patch.sh: line 129: gputemp: command not found
./raspi_mpeg_license_patch.sh: line 129: gputemp: command not found

**Comment by suuhm** [comment]
Ok you can ignore the errors. Looks judt fine. Can you test pls again after a reboot?

**Comment by nik2208** [comment]
I can't really appreciate the difference. How should I test it to notice an improvement in performance?

**Comment by suuhm** [comment]
you can check again please with: ```vcgencmd codec_enabled MPG2```

can you post the output of: ```md5sum /boot/start.elf*```

and: ```xxd /flash/start.elf*  | grep -i "47 *E9 *33 *36 *32 *48"```

In Raspbian you can check with tvheadend client etc .. dont know where the systeminfo is, maybe googling can help here to double check :)

**Comment by nik2208** [comment]
exactly.. I supposed tvheadend could get a boost in performance. maybe it depends on the nature of the streaming? I'm not so keen on the matter.. what kind of stream would get benefits from the hardware encoding? would the dvb-t/t2 do?

I'll post the output of the command as soon as I can

**Comment by suuhm** [comment]
Did you used this to install right the tvh-server on debian/raspbian 10 buster?

```
sudo apt -y install coreutils wget apt-transport-https lsb-release ca-certificates

sudo wget -qO- https://doozer.io/keys/tvheadend/tvheadend/pgp | sudo apt-key add -

echo "deb http://apt.tvheadend.org/stable raspbian-stretch main" | sudo tee -a /etc/apt/sources.list.d/tvheadend.list

sudo apt update

sudo apt install tvheadend
```

I test it with the DVB-C Input -> HTSP Stream and on Kodi Client: So without Hardware encoding patched you got only audio and no picture out.

Here you got some client , for example VLC is always pissible: https://tvheadend.org/projects/tvheadend/wiki/Clients

**Comment by nik2208** [comment]
if I'm not mistaken on latest raspi os theres no need to add a source list, so I must have simply run apt install tvheadend.
I use plane raspi os as nas, plex, and dvb-t2 receiver. cpus are almost idle all the time (even when streaming 4k plex files) exept when straming live tv, from plex or tvheadend indistinguishably

**Comment by suuhm** [comment]
> if I'm not mistaken on latest raspi os theres no need to add a source list, so I must have simply run apt install tvheadend. I use plane raspi os as nas, plex, and dvb-t2 receiver. cpus are almost idle all the time (even when streaming 4k plex files) exept when straming live tv, from plex or tvheadend indistinguishably

yes, maybe there's no need of the sources list. An yes, the Server is almost idling all the time, thats ok.
But if you have a HTSP client you'll need mpeg encoding

**Comment by nik2208** [comment]
server side encoding you mean.. ok.. and what kind of encoding does the cpu performs for dvb-t/t2? is it mpeg2 or vc1?

**Comment by suuhm** [comment]
No, the encoding side is the client side. The server can perform with minimum ressources.
The HTSP stream is based on MPEG encoding, VC1 is some ms codec.

DVBT/2 is here not important for..

**Comment by nik2208** [comment]
so what happens to me shouldnt happen, since my raspberry is only server, right?

**Comment by suuhm** [comment]
yes
