### ISSUE TITLE
new hex string

### ISSUE THREAD

**Issue by fadern** [suuhm/raspi_mpeg_license_patch.sh#3]
Hi,

There's a new hex string to find in the latest elf.

`search for 47E934363248
after this hex string:
if you have 3C18 replace 18 with 1F
if you have 1D18 replace 18 with 1F`

https://github.com/rapi3/raspi-keygen

**Comment by suuhm** [comment]
thx fadern, just commited here: https://github.com/suuhm/raspi_mpeg_license_patch.sh/commit/fe78c4a136b86652fadb46145dbf20c97ec16f99
