### ISSUE TITLE
codecs still disabled after patching

### ISSUE THREAD

**Issue by pepijn999** [suuhm/raspi_mpeg_license_patch.sh#4]
After I run the script (Raspberry pi 3B+, OSMC) the codecs are stil disabled, as indicated by the check:
```
   ____________________________________________________ 
  |><><><><><><><><><><><><><><><><><><><><><><><><><><|
  |  raspi_mpeg_license_patch v0.3b - (c)2021 suuhm    |
  |____________________________________________________|
                                                        
* Getting some necessary tools, maybe this take some time...
Tools already just here, continue...
* First check mpeg2/vc activated?
MPG2=disabled
WVC1=disabled


* Getting Hexstring... May take some time...

* Already Patched


* Check state xxd location +/- 1 line:
000b7440: 9a18 1060 009e 7f00 47e9 3247 504d 1018  ...`....G.2GPM..
000b7450: 02e8 3336 3248 47e9 3336 3248 091f 47e9  ..362HG.362H..G.
000b7460: 3447 504d 0518 47e9 3143 5657 c918 0060  4GPM..G.1CVW...`

* get GPUtemp every 5 secs... (STOP with Ctrl+C)
```
Am I doing something wrong?

**Comment by suuhm** [comment]
1. can you please post the command-line you've used?

2. Also did you restart after patching?

**Comment by pepijn999** [comment]
I used the --patch-now and --os=osmc flags, and did restart after patching. however with the new update of the script it seem to have worked :). (something else did break though so now I cannot play anything at all but that might have been caused by my earlier attempts)

**Comment by pepijn999** [comment]
overwriting the start_x.elf with a fresh one and re-patching worked :D

**Comment by suuhm** [comment]
glad that its work with the updated version, hf
