### ISSUE TITLE
LibreELEC 9 and 10 - $HS empty

### ISSUE THREAD

**Issue by cyberkeiler** [suuhm/raspi_mpeg_license_patch.sh#6]
On both Raspi 3 B+ with libreELEC 9.x and current 10.x patching failed:
`./raspi_mpeg_license_patch.sh --patch-now --os=libreelec`

and following output:

  ```
    ____________________________________________________ 
    |><><><><><><><><><><><><><><><><><><><><><><><><><><|
    |  raspi_mpeg_license_patch v0.4b - (c)2022 suuhm    |
    |____________________________________________________|
                                                          
* Getting some necessary tools, maybe this take some time...

[*] First check mpeg2/vc activated?
MPG2=disabled
WVC1=disabled

[+] Getting Hexstring... May take some time...

Using hexdump (beta)
[!] Not patched (0x) continue...

[*] set up patch now () ...
bash: 3: unknown operand
bash: 4: unknown operand
[!] Something went wrong, exit now..
```

As you can see $HS is empty.

Maybe same issue like #5 on raspbian?

-- EDIT --
Since on libreelec your script uses hexdump, I investigated further and found the REGEX not matching due to a line break in the hexdump output. Maybe the start.elf Version changed?

`REGEX2=".*47\ *e9\ *3(3|4)\ *36\ *32\ *48\ *(1d|3c)\ *(18|1f)\ .*"`

but you can see between 32 and 48 there ist the linechange.

...
000b788f  c0 02 e8 33 36 32 48 07  80 22 48 **47 e9 34 36 32**  _|...362H.."HG.462|
000b789f_  **48 1d 18** 47 e9 30 43 56  4d 19 18 47 e9 34 47 50  |H..G.0CVM..G.4GP|
...

REGEX of ".*48\ *(1d|3c)\ *(18|1f)\ .*" seems to be an unique hit in my start.elf version, so maybe the script can be changed.

Or use a Hex Editor (like Hex Fiend on Mac OS) and just replaced `47 E9 34 36 32 48 1D 18` by `47 E9 34 36 32 48 1D 1F` manually - tested successfully.

**Comment by suuhm** [comment]
Hi i've just added some fixes to prevent these linebreak failures. Maybe you can test and review?

Nightly beta: (Not tested yet)

https://github.com/suuhm/raspi_mpeg_license_patch.sh/blob/nightly/raspi_mpeg_license_patch.sh

https://github.com/suuhm/raspi_mpeg_license_patch.sh/commit/bec2a991081bb27d8ac86e3911216c64436ee43f
